import faintingGoatInnImg from './assets/fainting-goat-inn.jpg';
import type { Location } from './types/Location';

export const mockLocations: Location[] = [
  {
    id: 1,
    name: 'The Haunted Hotel',
    img: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    desc: 'Spend a night where the spirits never rest.',
    address: '13 Ghost Lane',
    city: 'Spooksville',
    state: 'MA',
    country: 'USA',
    features: ['Free WiFi', 'Breakfast Included', 'Pet Friendly'],
    history:
      'Built in 1890, this hotel is rumored to be haunted by its original owner and several guests who never checked out.',
    reviews: [
      {
        user: 'Jane Doe',
        rating: 5,
        comment: 'I heard footsteps at midnight! Spooky and fun stay.',
        date: '2024-06-01',
      },
      {
        user: 'Ghost Hunter',
        rating: 4,
        comment: 'Saw a shadowy figure in the hallway. Will return!',
        date: '2024-06-02',
      },
    ],
    latitude: 42.3601,
    longitude: -71.0589,
    website: 'https://hauntedhotel.example.com',
    contactEmail: 'info@hauntedhotel.com',
    isFeatured: false,
  },
  {
    id: 2,
    name: 'Cryptid Cabin',
    img: 'https://images.unsplash.com/photo-1464983953574-0892a716854b?auto=format&fit=crop&w=600&q=80',
    desc: 'Deep in the woods, something lurks...',
    address: '99 Mystery Rd',
    city: 'Pine Hollow',
    state: 'WA',
    country: 'USA',
    features: ['Fireplace', 'Mountain View'],
    history: 'Locals say a cryptid roams these woods. The cabin is a favorite for monster hunters.',
    reviews: [],
    latitude: 47.6062,
    longitude: -122.3321,
    isFeatured: false,
  },
  {
    id: 3,
    name: 'Ghostly Manor',
    img: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=600&q=80',
    desc: 'Echoes of the past await inside.',
    isFeatured: false,
  },
  {
    id: 4,
    name: 'Specter Springs',
    img: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80',
    desc: 'A haunted spa with ghostly guests.',
    isFeatured: false,
  },
  {
    id: 5,
    name: 'Witchlight Woods',
    img: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=600&q=80',
    desc: 'Strange lights and eerie sounds fill these woods.',
    isFeatured: false,
  },
  {
    id: 6,
    name: 'Phantom Lighthouse',
    img: 'https://unsplash.com/photos/spooky-night-in-a-forest-with-fog-and-an-evil-spirit-with-red-light-among-the-trees-halloween-concept-apparition-terror-and-fear-3d-rendering-M3Fiat-I5dY',
    desc: 'A beacon for lost souls on stormy nights.',
    isFeatured: false,
  },
  {
    id: 7,
    name: 'Banshee Bridge',
    img: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80',
    desc: 'Cross at your own risk—wailing awaits.',
    isFeatured: false,
  },
  {
    id: 8,
    name: 'Ghoul Gulch',
    img: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?auto=format&fit=crop&w=600&q=80',
    desc: 'A canyon echoing with ghostly laughter.',
    isFeatured: false,
  },
  {
    id: 9,
    name: 'Poltergeist Palace',
    img: 'https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=600&q=80',
    desc: 'Objects move on their own in this haunted mansion.',
    isFeatured: false,
  },
  {
    id: 10,
    name: 'The Fainting Goat Inn',
    img: faintingGoatInnImg,
    desc: 'The guestbook is filled with rave reviews peppered with experiences that will send a shiver down your spine.',
    address: '1 Bleat Street',
    city: 'Goatville',
    state: 'CO',
    country: 'USA',
    features: ['Farm-to-Table Breakfast', 'Ghost Tours', 'Petting Zoo'],
    history:
      'Once a quiet farmhouse, now a destination for thrill-seekers and goat lovers alike. Some say the goats see things we cannot...',
    reviews: [
      {
        user: 'Billy',
        rating: 5,
        comment: 'The goats were adorable and the ghost tour was chilling!',
        date: '2024-06-03',
      },
    ],
    latitude: 39.7392,
    longitude: -104.9903,
    website: 'https://www.faintinggoatislandinn.com',
    contactEmail: 'faintinggoatinn@gmail.com',
    isFeatured: true,
  },
];
